/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eCirculo;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;

/**
 *
 * @author paveg
 */
public class PnlContenedor extends javax.swing.JPanel {
    private Circulo[] circulos;
    /**
     * Creates new form PnlContenedor
     */
    
    
    public PnlContenedor(Circulo[] listaCirculos) {
        initComponents();
        this.circulos=listaCirculos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void paint(Graphics g){
        for (int i = 0; i < circulos.length; i++) {
            if(circulos[i]==null) break;
            Circulo circuloADibujar=circulos[i];
            g.setColor(circuloADibujar.getColor());
            g.fillOval(circuloADibujar.centro.getX()-circuloADibujar.getRadio(),
                    circuloADibujar.centro.getY()-circuloADibujar.getRadio(),
                    circuloADibujar.getRadio()*2,
                    circuloADibujar.getRadio()*2);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
